<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

In [1]:
import numpy as np

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

# storing as Python List

In [3]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

# storing as Numpy Arrays
# For both list the order/position matters

In [4]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

# Storing using the dictionary
# Key and associated values is separated by a colon
# Uses one structure vs the other two that each used 2 lists

## 1.2 Accessing data from a list (or array)

In [ ]:
# Python is a zero-indexed language -> It starts counting from 0

In [9]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

py_real_names[0] # It reads the first name in py_real_name list

'Natasha Romanoff'

In [10]:
py_super_names[0] # It reads the first name in py_super_name list

'Black Widow'

In [11]:
py_super_names[2]    # Forward indexing 
                     # We need to know the size 
                     # beforehand for this to work.

'Doctor Strange'

In [12]:
py_super_names[-1]   # Reverse indexing
                     # Able to access the last element w/o needing to
                     # know the list size

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [14]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

# The real name of the superhero is the 'key'
# In the dictionary a 'key' is tied to a 'value'

In [15]:
superhero_info["Natasha Romanoff"] # Request for the 'value' by using the 'key'

'Black Widow'

In [16]:
superhero_info.keys() # To list out all the 'key'

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [17]:
superhero_info.values() # To list out all the 'value'

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [18]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# 2 Lists vs. Arrays

## 2.1 Size

In [21]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [22]:
len(py_list_2d) # The function len() lets you know how many elements are in
                # the list

10

In [23]:
len(np_array_2d) # The function len() lets you know how many elements are in
                 # the list

10

In [24]:
np_array_2d.shape #shape is not a function but an attribute of Numpy array

(10, 2)

## 2.2 Arrays are fussy about type

In [25]:
# NumPy arrays only tolerate a single type

py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [26]:
py_list

[1, 1.5, 'A']

In [27]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [3]:
import numpy as np
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [5]:
np_array + 10 # Adds 10 to all values in the list

array([11, 12, 13, 14, 15])

## 2.4 Adding another list

In [6]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [9]:
py_list_1 + py_list_2 # Adding list = increases the size of the list 
                      # Increasing the number of elements in the list

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [10]:
np_array_1 + np_array_2 # Adding arrays sums the elements

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [11]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [14]:
py_list*2 # Multiplying the list = increases the size of the list 
          # Increasing the number of elements in the list

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [15]:
np_array*2 # Multiplying arrays multiples the elements

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [16]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [18]:
py_list**2                      # Won't work!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [19]:
np_array**2 # Squares all the elements

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [20]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [21]:
py_list ==3 # Reply is given but dont know what was the question asked

False

In [23]:
np_array == 3  # compares all the element to the question

array([False, False,  True, False, False])

In [25]:
np_array > 3  # compares all the element to the question

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [27]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [33]:
print(np_array.sum()) # can do a lot of different maths with arrays
print(np_array.max())
print(np_array.min())
print(np_array.mean())
print(np_array.std())

15
5
1
3.0
1.4142135623730951


# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes